package name.abuchen.portfolio.ui;

public enum DataType
{

    NAME, ISIN, WKN, TICKER_SYMBOL, TRANSACTION_TYPE,
    DATE, FUTURE_DATE,
    CURRENCY,
    NUM_SHARES,
    QUOTE, QUOTE_DIFF, QUOTE_PERCENT, MONEY, MONEY_DIFF,
    IS_RETIRED,
    OTHER_ENUM, OTHER_TEXT, OTHER_BOOLEAN, OTHER_NUMBER, OTHER;

}
